import datetime

SEED = 1337
AUTOCORRECTION_EPOCHS = 250
AUTOCORRECTION_ENCODING_DIM = 21
AUTOCORRECTION_SEED = 13241
ITERATIONS = 300
WARMUP = 0
SCORE_WARMUP = 0
SCORE_SAVE_INTERVAL = 1
NUMBER_OF_PROCESSES = 4
ITERATIONS_IN_ONE_BATCH = 160
MODEL = 'basic'
DISTRIBUTED = 'single'
SAVE_TIME_DELTA_MIN = datetime.timedelta(seconds=60)
SAVE_TRACE = True
SAVE_WARMUP = True
SAVE_BACKUP = False
A0 = 1.0
B0 = 1.0
E0 = 0.1
F0 = 0.1

SKIP = 10
GENE_SAMPLE_RANGES = ('ALL', 'ALL')